"""
Django settings for elegant_interiors project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-0^d$eg-1$&h1yby#sya+n%a2dw9e95f-&p39_%g=k&9vd*+99@"

# SECURITY WARNING: don't run with debug turned on in production!
ALLOWED_HOSTS = [
    'fourthdimensions.in',
    'www.fourthdimensions.in',
    '62.72.58.73',
    'localhost',
    '127.0.0.1'
]
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
    "admin_volt",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'main.middleware.VisitorTrackingMiddleware',
]

ROOT_URLCONF = "elegant_interiors.urls"

# Update TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "elegant_interiors.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Add STATICFILES_DIRS
STATIC_URL = '/static/'
STATIC_ROOT = '/var/www/elegant_interiors/static'
MEDIA_URL = '/media/'
MEDIA_ROOT = '/var/www/elegant_interiors/media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files configuration
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Admin Volt settings
ADMIN_VOLT = {
    'SITE_TITLE': 'Elegant Interiors',
    'SITE_BRAND': 'Elegant Interiors',
    'SITE_ICON': None,  # Upload your logo later
    'WELCOME_MESSAGE': 'Welcome to Elegant Interiors Dashboard',
    
    # Dashboard Widgets
    'DASHBOARD_WIDGETS': {
        'contacts': True,
        'recent_actions': True,
        'quick_actions': True,
        'charts': True,
    },
    
    # Theme Settings
    'THEME': {
        'primary_color': '#ca8a04',
        'secondary_color': '#854d0e',
        'accent_color': '#fcd34d',
    },
    
    # Sidebar Menu
    'MENU': [
        {
            'label': 'Dashboard',
            'icon': 'dashboard',
            'url': 'admin:index',
        },
        {
            'label': 'Contacts',
            'icon': 'contacts',
            'models': [
                'main.contact',
            ],
        },
        {
            'label': 'Users',
            'icon': 'people',
            'models': [
                'auth.user',
                'auth.group',
            ],
        },
    ],
}

JAZZMIN_SETTINGS = {
    "site_title": "4th Dimension",
    "site_header": "4th Dimension",
    "site_brand": "4th Dimension",
    "welcome_sign": "Welcome to the 4th Dimension Dashboard",
    "copyright": "4th Dimension Ltd",
    
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
        {"name": "View Site", "url": "/"},
    ],
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "main.contact": "fas fa-envelope",
        "main.sitevisit": "fas fa-chart-line",
        "main.category": "fas fa-folder",
        "main.project": "fas fa-project-diagram"
    },
    
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "form_submit_label": "Save",
    "submit_sticky": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-warning",
    "navbar": "navbar-warning navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": True,
    "submit_sticky": True,
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": True,
}
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
