# Generated by Django 5.1.2 on 2024-11-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_responded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="contact",
            name="estimate_type",
            field=models.CharField(max_length=50),
        ),
    ]
