# Generated by Django 5.1.2 on 2024-11-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contact_is_responded_alter_contact_estimate_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.CharField(max_length=500)),
                ("path", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
