# Generated by Django 5.1.2 on 2024-11-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_sitevisit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitevisit",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Site Visit",
                "verbose_name_plural": "Site Visits",
            },
        ),
    ]
